package xyz.chengzi.ooad.embeddable;

public enum SubmissionStatus {
    PENDING, COMPILING, COMPILE_ERROR, ACCEPTED, WRONG_ANSWER, RUNTIME_ERROR, TIME_LIMIT_EXCEEDED, MEMORY_LIMIT_EXCEEDED, SYSTEM_ERROR
}
